_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "1": epoch/accuracy
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/learning_rate
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_accuracy
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 53
                - 80
            "2":
                - 1
                - 2
                - 3
                - 5
                - 53
                - 80
            "3":
                - 2
                - 7
                - 16
                - 38
                - 55
            "4": 3.12.11
            "5": 0.20.1
            "8":
                - 1
            "12": 0.20.1
            "13": linux-x86_64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
architecture:
    value: EfficientNetV2B0
batch_size:
    value: 32
epochs:
    value: 100
input_shape:
    value:
        - 200
        - 200
        - 3
loss:
    value: categorical_crossentropy
num_classes:
    value: 2
optimizer:
    value: adam
